server:
  port: 8089

spring:
  application:
    name: shiro
  mvc:
    view:
      prefix: /
      suffix: .jsp

  # 数据库
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shiro?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: password
# MyBatis
mybatis:
  # 搜索指定包别名 默认不支持通配符 此处优化自定义MyBatisConfig配置
  type-aliases-package: com.fadedos.*.entity
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath:mapper/**/*Mapper.xml
  # 加载全局的配置文件 :骆驼命名/自动返回主键/log/cache等设置 MyBatisConfig中提取
  config-location: classpath:mybatis/mybatis-config.xml

# 日志级别
logging:
  level:
    com.fadedos: debug
    org.springframework: warn